<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Adventure.Kern\Adventure.Kern.csproj" />
    <ProjectReference Include="..\Adventure.Daten\Adventure.Daten.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\levels\*.txt" Link="levels\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
